### ISSUE TITLE
TypeError: Cannot read property 'pos' of undefined

### ISSUE THREAD

**Issue by blackjyn** [BowlerHatLLC/dts2as#6]
Got error like this :
![dts2aserror](https://cloud.githubusercontent.com/assets/6046191/11323387/de6279a2-9143-11e5-903b-f0f9aa07fc56.png)
I'm on WIndows 8.1 x64 with Node v.0.12.7

**Comment by joshtynjala** [comment]
Thanks for the bug report. I don't think I've tested with Node 0.12. I'll take a look soon. In the meantime, you might also try with a newer release of Node.

**Comment by joshtynjala** [comment]
Unfortunately, I cannot reproduce using the same environment. I also tried Windows 8.1 x64 with Node v0.12.7. I wonder what could be different...

**Comment by blackjyn** [comment]
Thanks Josh...
Upgraded to v5.1.0 (latest stable) , and still no luck 
![dts2aserroragain](https://cloud.githubusercontent.com/assets/6046191/11328689/cc5d7986-91c1-11e5-9774-0087eace0d5d.png)

**Comment by joshtynjala** [comment]
Could you share the contents of your pixi.js.d.ts file? Maybe the version you downloaded is different than mine somehow.

Also, I assume that you're using dts2as 0.6.1?

**Comment by blackjyn** [comment]
God... I'm sorry Josh.. Thanks for noticing the content. 
I was following your article on http://nextgenactionscript.com/tutorials/dts2as-typescript-definitions-with-actionscript/
So when I click the link that refer to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pixi.js/pixi.js.d.ts, unfortunately  my download manager treat this as direct URL to download, so that was what I downloaded. And the content is kinda like HTML tags, instead of valid TypeScript source file.

then I realize the actual file should be the raw content taken from https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/pixi.js/pixi.js.d.ts

Sorry for this stupid sh*t.. 
You might want to update your article lilbit, to avoid other users doing this. May be by suggesting them to install official TSD package manager.

Thank you!  :+1:  

![dtsok](https://cloud.githubusercontent.com/assets/6046191/11329579/82b9b646-91d0-11e5-9dee-7f0db8a8dbf0.png)
